[CI] don't set max heap space for java 17
setting to 512MB which is about half the size of the default value doesn't seem right.
this attempts to resolve build failures for java 17 builds caused by 
```
Error: 5,941 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:3.3.2:war (default-war) on project activemqBroker: Error assembling WAR: Problem creating war: Execution exception: Java heap space -> [Help 1]
Error: 5,941 [ERROR] Java heap space -> [Help 2]
Error: 5,943 [ERROR] java.lang.OutOfMemoryError: Java heap space
```